/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../views/AboutView.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    Icon_xxxxxxx: typeof import('./../components/icons/Icon_xxxxxxx.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WenLayout: typeof import('./../layout/WenLayout.vue')['default']
    WenLayoutMain: typeof import('./../layout/WenLayoutMain.vue')['default']
    WenTitlebar: typeof import('./../components/titlebar/WenTitlebar.vue')['default']
    WindowIcon: typeof import('./../components/titlebar/WindowIcon.vue')['default']
  }
}
