/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../views/AboutView.vue')['default']
    BasicLayout: typeof import('./../layout/BasicLayout/index.vue')['default']
    BlankLayout: typeof import('./../layout/BlankLayout/index.vue')['default']
    CarbonClose: typeof import('./../components/icon/CarbonClose.vue')['default']
    CarbonMoon: typeof import('./../components/icon/CarbonMoon.vue')['default']
    CarbonSettings: typeof import('./../components/icon/CarbonSettings.vue')['default']
    ColorCheckbox: typeof import('./../layout/components/theme-setting/drawer-content/global-theme/components/ColorCheckbox.vue')['default']
    DrawerButton: typeof import('./../layout/components/theme-setting/drawer-button/index.vue')['default']
    DrawerContent: typeof import('./../layout/components/theme-setting/drawer-content/index.vue')['default']
    GlobalConfig: typeof import('./../layout/components/theme-setting/drawer-content/global-config/index.vue')['default']
    GlobalContent: typeof import('./../layout/components/global-content/index.vue')['default']
    GlobalCopy: typeof import('./../layout/components/theme-setting/drawer-content/global-copy/index.vue')['default']
    GlobalFooter: typeof import('./../layout/components/global-footer/index.vue')['default']
    GlobalHeader: typeof import('./../layout/components/global-header/index.vue')['default']
    GlobalLayout: typeof import('./../layout/components/theme-setting/drawer-content/global-layout/index.vue')['default']
    GlobalSider: typeof import('./../layout/components/global-sider/index.vue')['default']
    GlobalTab: typeof import('./../layout/components/global-tab/index.vue')['default']
    GlobalTheme: typeof import('./../layout/components/theme-setting/drawer-content/global-theme/index.vue')['default']
    HeaderCompany: typeof import('./../layout/components/global-header/cpns/header-company.vue')['default']
    HeaderMenu: typeof import('./../layout/components/global-header/cpns/header-menu.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    IcBaselineWbSunny: typeof import('./../components/icon/IcBaselineWbSunny.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconFont: typeof import('./../components/icon/iconFont.vue')['default']
    IconIcOutlineCheck: typeof import('~icons/ic/outline-check')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    LayoutCheckBox: typeof import('./../layout/components/theme-setting/drawer-content/global-layout/components/LayoutCheckBox.vue')['default']
    LogosBitriseIcon: typeof import('./../components/icon/LogosBitriseIcon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/icon/svgIcon.vue')['default']
    TabBurger: typeof import('./../layout/components/global-tab/cpns/tab-burger.vue')['default']
    ThemeSetting: typeof import('./../layout/components/theme-setting/index.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    Welcome: typeof import('./../components/Welcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
