/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../views/AboutView.vue')['default']
    CajianzhuView: typeof import('./../views/CajianzhuView.vue')['default']
    FileManagerView: typeof import('./../views/FileManagerView.vue')['default']
    GaishuView: typeof import('./../views/GaishuView.vue')['default']
    HomeView: typeof import('./../views/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsView: typeof import('./../views/SettingsView.vue')['default']
    WenIconsSiderButtonElse: typeof import('./../components/icons/siderbutton/WenIconsSiderButtonElse.vue')['default']
    WenIconsSiderButtonIf: typeof import('./../components/icons/siderbutton/WenIconsSiderButtonIf.vue')['default']
    WenIconsSiderMenuGuangyu: typeof import('./../components/icons/sidermenu/WenIconsSiderMenuGuangyu.vue')['default']
    WenIconsSiderMenuHome: typeof import('./../components/icons/sidermenu/WenIconsSiderMenuHome.vue')['default']
    WenIconsSiderMenuHuodong: typeof import('./../components/icons/sidermenu/WenIconsSiderMenuHuodong.vue')['default']
    WenIconsSiderMenuQuanbu: typeof import('./../components/icons/sidermenu/WenIconsSiderMenuQuanbu.vue')['default']
    WenIconsSiderMenuSettings: typeof import('./../components/icons/sidermenu/WenIconsSiderMenuSettings.vue')['default']
    WenIconsSiderMenuWenjianjia: typeof import('./../components/icons/sidermenu/WenIconsSiderMenuWenjianjia.vue')['default']
    WenIconsSiderMenuXiangqing: typeof import('./../components/icons/sidermenu/WenIconsSiderMenuXiangqing.vue')['default']
    WenIconsTheme: typeof import('./../components/icons/WenIconsTheme.vue')['default']
    WenIconsWindowsClose: typeof import('./../components/icons/windows/WenIconsWindowsClose.vue')['default']
    WenIconsWindowsMaximize: typeof import('./../components/icons/windows/WenIconsWindowsMaximize.vue')['default']
    WenIconsWindowsMinimize: typeof import('./../components/icons/windows/WenIconsWindowsMinimize.vue')['default']
    WenLayout: typeof import('./../layout/WenLayout.vue')['default']
    WenLayoutMain: typeof import('./../layout/WenLayoutMain.vue')['default']
    WenLayoutSider: typeof import('./../layout/WenLayoutSider.vue')['default']
    WorkplaceView: typeof import('./../views/WorkplaceView.vue')['default']
  }
}
